[2024-10-11T00:00:04.358+0000] {processor.py:186} INFO - Started process (PID=802) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:00:04.360+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:00:04.382+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:00:04.380+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:00:04.516+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:00:04.482+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.utiles import creacion_spark, jdbc_properties, conection_url
  File "/opt/airflow/dags/modules/utiles.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:00:04.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:00:04.737+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.421 seconds
[2024-10-11T00:00:35.011+0000] {processor.py:186} INFO - Started process (PID=809) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:00:35.013+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:00:35.036+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:00:35.033+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:00:35.125+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:00:35.107+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.utiles import creacion_spark, jdbc_properties, conection_url
  File "/opt/airflow/dags/modules/utiles.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:00:35.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:00:35.186+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.206 seconds
[2024-10-11T00:01:06.013+0000] {processor.py:186} INFO - Started process (PID=816) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:01:06.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:01:06.017+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:01:06.017+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:01:06.054+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:01:06.045+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.utiles import creacion_spark, jdbc_properties, conection_url
  File "/opt/airflow/dags/modules/utiles.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:01:06.056+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:01:06.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.066 seconds
[2024-10-11T00:01:36.626+0000] {processor.py:186} INFO - Started process (PID=824) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:01:36.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:01:36.633+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:01:36.632+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:01:36.695+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:01:36.677+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.utiles import creacion_spark, jdbc_properties, conection_url
  File "/opt/airflow/dags/modules/utiles.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:01:36.698+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:01:37.038+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.421 seconds
[2024-10-11T00:02:07.310+0000] {processor.py:186} INFO - Started process (PID=831) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:02:07.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:02:07.315+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:02:07.314+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:02:07.364+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:02:07.352+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.utiles import creacion_spark, jdbc_properties, conection_url
  File "/opt/airflow/dags/modules/utiles.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:02:07.368+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:02:07.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.177 seconds
[2024-10-11T00:02:37.532+0000] {processor.py:186} INFO - Started process (PID=838) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:02:37.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:02:37.536+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:02:37.536+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:02:37.588+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:02:37.575+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.utiles import creacion_spark, jdbc_properties, conection_url
  File "/opt/airflow/dags/modules/utiles.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:02:37.592+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:02:37.612+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.085 seconds
[2024-10-11T00:03:07.760+0000] {processor.py:186} INFO - Started process (PID=845) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:03:07.762+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:03:07.765+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:03:07.764+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:03:07.810+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:03:07.796+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.utiles import creacion_spark, jdbc_properties, conection_url
  File "/opt/airflow/dags/modules/utiles.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:03:07.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:03:07.833+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.081 seconds
[2024-10-11T00:03:38.076+0000] {processor.py:186} INFO - Started process (PID=852) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:03:38.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:03:38.080+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:03:38.080+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:03:38.129+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:03:38.116+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.utiles import creacion_spark, jdbc_properties, conection_url
  File "/opt/airflow/dags/modules/utiles.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:03:38.133+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:03:38.153+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.085 seconds
[2024-10-11T00:04:08.528+0000] {processor.py:186} INFO - Started process (PID=859) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:04:08.530+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:04:08.532+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:04:08.532+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:04:08.591+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:04:08.580+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.utiles import creacion_spark, jdbc_properties, conection_url
  File "/opt/airflow/dags/modules/utiles.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:04:08.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:04:08.612+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.088 seconds
[2024-10-11T00:04:38.815+0000] {processor.py:186} INFO - Started process (PID=866) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:04:38.816+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:04:38.818+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:04:38.818+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:04:38.848+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:04:38.841+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.utiles import creacion_spark, jdbc_properties, conection_url
  File "/opt/airflow/dags/modules/utiles.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:04:38.850+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:04:38.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.058 seconds
[2024-10-11T00:05:09.553+0000] {processor.py:186} INFO - Started process (PID=873) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:05:09.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:05:09.557+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:05:09.557+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:05:09.619+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:05:09.593+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.utiles import creacion_spark, jdbc_properties, conection_url
  File "/opt/airflow/dags/modules/utiles.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:05:09.623+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:05:09.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.097 seconds
[2024-10-11T00:05:40.496+0000] {processor.py:186} INFO - Started process (PID=880) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:05:40.498+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:05:40.500+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:05:40.500+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:05:40.561+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:05:40.548+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.utiles import creacion_spark, jdbc_properties, conection_url
  File "/opt/airflow/dags/modules/utiles.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:05:40.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:05:40.584+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.095 seconds
[2024-10-11T00:06:10.757+0000] {processor.py:186} INFO - Started process (PID=887) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:06:10.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:06:10.762+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:06:10.762+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:06:10.803+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:06:10.793+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.utiles import creacion_spark, jdbc_properties, conection_url
  File "/opt/airflow/dags/modules/utiles.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:06:10.806+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:06:10.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.073 seconds
[2024-10-11T00:06:41.032+0000] {processor.py:186} INFO - Started process (PID=894) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:06:41.033+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:06:41.036+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:06:41.035+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:06:41.083+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:06:41.072+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.utiles import creacion_spark, jdbc_properties, conection_url
  File "/opt/airflow/dags/modules/utiles.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:06:41.086+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:06:41.104+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.077 seconds
[2024-10-11T00:07:11.357+0000] {processor.py:186} INFO - Started process (PID=901) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:07:11.358+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:07:11.360+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:07:11.360+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:07:11.391+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:07:11.379+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.utiles import creacion_spark, jdbc_properties, conection_url
  File "/opt/airflow/dags/modules/utiles.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:07:11.394+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:07:11.409+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.058 seconds
[2024-10-11T00:07:41.359+0000] {processor.py:186} INFO - Started process (PID=908) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:07:41.361+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:07:41.365+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:07:41.364+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:07:41.387+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:07:41.385+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6
    from modules import creacion_df, transformaciones, carga_datos,
                                                                   ^
SyntaxError: trailing comma not allowed without surrounding parentheses
[2024-10-11T00:07:41.388+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:07:41.410+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.058 seconds
[2024-10-11T00:08:11.644+0000] {processor.py:186} INFO - Started process (PID=915) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:08:11.645+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:08:11.649+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:08:11.648+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:08:11.668+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:08:11.667+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6
    from modules import creacion_df, transformaciones, carga_datos,
                                                                   ^
SyntaxError: trailing comma not allowed without surrounding parentheses
[2024-10-11T00:08:11.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:08:11.691+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.053 seconds
[2024-10-11T00:08:42.069+0000] {processor.py:186} INFO - Started process (PID=922) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:08:42.071+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:08:42.076+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:08:42.075+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:08:42.100+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:08:42.098+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6
    from modules import creacion_df, transformaciones, carga_datos,
                                                                   ^
SyntaxError: trailing comma not allowed without surrounding parentheses
[2024-10-11T00:08:42.101+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:08:42.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.068 seconds
[2024-10-11T00:09:10.341+0000] {processor.py:186} INFO - Started process (PID=929) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:09:10.342+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:09:10.344+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:09:10.344+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:09:10.359+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:09:10.358+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6
    from modules import creacion_df, transformaciones, carga_datos,
                                                                   ^
SyntaxError: trailing comma not allowed without surrounding parentheses
[2024-10-11T00:09:10.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:09:10.377+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.042 seconds
[2024-10-11T00:09:14.473+0000] {processor.py:186} INFO - Started process (PID=930) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:09:14.475+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:09:14.478+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:09:14.478+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:09:14.603+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:09:14.585+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:09:14.609+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:09:14.639+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.173 seconds
[2024-10-11T00:09:44.968+0000] {processor.py:186} INFO - Started process (PID=937) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:09:45.192+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:09:45.207+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:09:45.204+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:09:45.875+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:09:45.854+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:09:45.880+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:09:45.912+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.950 seconds
[2024-10-11T00:10:16.708+0000] {processor.py:186} INFO - Started process (PID=944) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:10:16.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:10:16.714+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:10:16.713+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:10:16.797+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:10:16.768+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:10:16.804+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:10:16.832+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.132 seconds
[2024-10-11T00:10:47.012+0000] {processor.py:186} INFO - Started process (PID=951) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:10:47.014+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:10:47.018+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:10:47.017+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:10:47.117+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:10:47.097+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:10:47.123+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:10:47.241+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.234 seconds
[2024-10-11T00:11:17.372+0000] {processor.py:186} INFO - Started process (PID=958) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:11:17.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:11:17.378+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:11:17.377+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:11:17.444+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:11:17.427+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:11:17.447+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:11:17.478+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.113 seconds
[2024-10-11T00:11:47.783+0000] {processor.py:186} INFO - Started process (PID=965) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:11:47.784+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:11:47.788+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:11:47.788+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:11:47.883+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:11:47.866+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:11:47.890+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:11:47.910+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.133 seconds
[2024-10-11T00:12:18.045+0000] {processor.py:186} INFO - Started process (PID=972) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:12:18.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:12:18.049+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:12:18.049+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:12:18.121+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:12:18.108+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:12:18.125+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:12:18.144+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.105 seconds
[2024-10-11T00:12:48.328+0000] {processor.py:186} INFO - Started process (PID=979) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:12:48.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:12:48.331+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:12:48.331+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:12:48.383+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:12:48.376+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:12:48.407+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:12:48.429+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.107 seconds
[2024-10-11T00:13:18.697+0000] {processor.py:186} INFO - Started process (PID=986) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:13:18.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:13:18.701+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:13:18.701+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:13:18.768+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:13:18.749+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from modules.modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:13:18.772+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:13:18.795+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.104 seconds
[2024-10-11T00:13:49.200+0000] {processor.py:186} INFO - Started process (PID=993) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:13:49.203+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:13:49.207+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:13:49.207+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:13:49.273+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:13:49.259+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:13:49.277+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:13:49.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.108 seconds
[2024-10-11T00:14:19.745+0000] {processor.py:186} INFO - Started process (PID=1000) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:14:19.746+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:14:19.750+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:14:19.750+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:14:19.806+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:14:19.791+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:14:19.811+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:14:19.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.088 seconds
[2024-10-11T00:14:50.854+0000] {processor.py:186} INFO - Started process (PID=1007) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:14:50.855+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:14:50.859+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:14:50.859+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:14:50.916+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:14:50.902+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:14:50.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:14:50.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.094 seconds
[2024-10-11T00:15:21.121+0000] {processor.py:186} INFO - Started process (PID=1014) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:15:21.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:15:21.125+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:15:21.125+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:15:21.184+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:15:21.169+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:15:21.190+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:15:21.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.095 seconds
[2024-10-11T00:15:51.446+0000] {processor.py:186} INFO - Started process (PID=1021) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:15:51.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:15:51.453+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:15:51.452+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:15:51.535+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:15:51.512+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:15:51.543+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:15:51.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.135 seconds
[2024-10-11T00:16:22.345+0000] {processor.py:186} INFO - Started process (PID=1028) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:16:22.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:16:22.350+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:16:22.350+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:16:22.406+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:16:22.390+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:16:22.410+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:16:22.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.585 seconds
[2024-10-11T00:16:53.282+0000] {processor.py:186} INFO - Started process (PID=1035) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:16:53.284+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:16:53.288+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:16:53.288+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:16:53.353+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:16:53.334+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:16:53.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:16:53.395+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.122 seconds
[2024-10-11T00:17:23.496+0000] {processor.py:186} INFO - Started process (PID=1042) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:17:23.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:17:23.500+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:17:23.500+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:17:23.558+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:17:23.543+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .modificaciones import transformaciones
  File "/opt/airflow/dags/modules/modificaciones.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:17:23.563+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:17:23.590+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.101 seconds
[2024-10-11T00:17:53.830+0000] {processor.py:186} INFO - Started process (PID=1049) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:17:53.834+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:17:53.837+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:17:53.837+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:17:53.939+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:17:53.924+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:17:53.943+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:17:53.971+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.146 seconds
[2024-10-11T00:18:24.215+0000] {processor.py:186} INFO - Started process (PID=1056) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:18:24.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:18:24.220+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:18:24.220+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:18:24.283+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:18:24.267+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:18:24.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:18:24.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.101 seconds
[2024-10-11T00:18:54.739+0000] {processor.py:186} INFO - Started process (PID=1063) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:18:54.741+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:18:54.747+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:18:54.746+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:18:54.802+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:18:54.788+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:18:54.806+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:18:54.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.094 seconds
[2024-10-11T00:19:25.283+0000] {processor.py:186} INFO - Started process (PID=1070) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:19:25.284+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:19:25.287+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:19:25.287+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:19:25.313+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:19:25.306+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:19:25.315+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:19:25.330+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.052 seconds
[2024-10-11T00:19:56.341+0000] {processor.py:186} INFO - Started process (PID=1077) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:19:56.342+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:19:56.346+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:19:56.345+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:19:56.389+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:19:56.377+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:19:56.392+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:19:56.417+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.084 seconds
[2024-10-11T00:20:26.618+0000] {processor.py:186} INFO - Started process (PID=1085) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:20:26.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:20:26.631+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:20:26.630+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:20:26.693+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:20:26.675+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:20:26.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:20:26.734+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.128 seconds
[2024-10-11T00:20:57.016+0000] {processor.py:186} INFO - Started process (PID=1092) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:20:57.018+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:20:57.022+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:20:57.021+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:20:57.082+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:20:57.071+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:20:57.086+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:20:57.120+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.118 seconds
[2024-10-11T00:21:27.404+0000] {processor.py:186} INFO - Started process (PID=1099) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:21:27.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:21:27.408+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:21:27.408+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:21:27.453+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:21:27.441+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:21:27.457+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:21:27.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.078 seconds
[2024-10-11T00:21:57.703+0000] {processor.py:186} INFO - Started process (PID=1106) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:21:57.704+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:21:57.708+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:21:57.707+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:21:57.754+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:21:57.743+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:21:57.759+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:21:57.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.081 seconds
[2024-10-11T00:22:27.941+0000] {processor.py:186} INFO - Started process (PID=1113) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:22:27.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:22:27.946+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:22:27.945+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:22:27.995+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:22:27.981+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:22:27.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:22:28.017+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.082 seconds
[2024-10-11T00:22:58.210+0000] {processor.py:186} INFO - Started process (PID=1120) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:22:58.211+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:22:58.215+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:22:58.214+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:22:58.285+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:22:58.271+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:22:58.289+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:22:58.316+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.114 seconds
[2024-10-11T00:23:28.553+0000] {processor.py:186} INFO - Started process (PID=1127) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:23:28.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:23:28.558+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:23:28.557+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:23:28.610+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:23:28.597+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:23:28.613+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:23:28.633+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.085 seconds
[2024-10-11T00:23:58.828+0000] {processor.py:186} INFO - Started process (PID=1134) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:23:58.830+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:23:58.833+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:23:58.833+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:23:58.893+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:23:58.878+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:23:58.898+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:23:58.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.098 seconds
[2024-10-11T00:24:30.574+0000] {processor.py:186} INFO - Started process (PID=1142) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:24:30.576+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:24:30.579+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:24:30.579+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:24:31.959+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:24:31.931+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:24:31.963+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:24:32.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 1.447 seconds
[2024-10-11T00:25:02.184+0000] {processor.py:186} INFO - Started process (PID=1149) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:25:02.186+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:25:02.189+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:25:02.189+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:25:02.269+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:25:02.251+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:25:02.274+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:25:02.379+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.201 seconds
[2024-10-11T00:25:32.640+0000] {processor.py:186} INFO - Started process (PID=1156) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:25:32.641+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:25:32.645+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:25:32.645+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:25:32.695+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:25:32.683+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:25:32.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:25:32.718+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.083 seconds
[2024-10-11T00:26:02.951+0000] {processor.py:186} INFO - Started process (PID=1164) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:26:02.953+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:26:02.957+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:26:02.956+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:26:03.036+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:26:03.019+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:26:03.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:26:03.079+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.133 seconds
[2024-10-11T00:26:33.378+0000] {processor.py:186} INFO - Started process (PID=1172) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:26:33.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:26:33.424+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:26:33.424+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:26:33.753+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:26:33.740+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:26:33.757+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:26:33.776+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.404 seconds
[2024-10-11T00:27:04.342+0000] {processor.py:186} INFO - Started process (PID=1178) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:27:04.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:27:04.348+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:27:04.347+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:27:04.384+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:27:04.375+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:27:04.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:27:04.406+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.069 seconds
[2024-10-11T00:27:34.694+0000] {processor.py:186} INFO - Started process (PID=1185) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:27:34.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:27:34.735+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:27:34.732+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:27:34.923+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:27:34.891+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:27:34.930+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:27:35.698+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 1.013 seconds
[2024-10-11T00:28:06.224+0000] {processor.py:186} INFO - Started process (PID=1192) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:28:06.226+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:28:06.229+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:28:06.228+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:28:06.299+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:28:06.282+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:28:06.303+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:28:06.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.108 seconds
[2024-10-11T00:28:36.485+0000] {processor.py:186} INFO - Started process (PID=1199) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:28:36.486+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:28:36.489+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:28:36.489+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:28:36.533+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:28:36.521+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:28:36.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:28:36.553+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.075 seconds
[2024-10-11T00:29:06.889+0000] {processor.py:186} INFO - Started process (PID=1207) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:29:06.890+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:29:06.895+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:29:06.894+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:29:06.948+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:29:06.936+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
  File "/opt/airflow/dags/modules/armado_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:29:06.951+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:29:07.025+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.141 seconds
[2024-10-11T00:29:37.216+0000] {processor.py:186} INFO - Started process (PID=1215) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:29:37.218+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:29:37.222+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:29:37.222+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:29:37.258+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:29:37.246+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
ModuleNotFoundError: No module named 'modules.armado_df'
[2024-10-11T00:29:37.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:29:37.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.078 seconds
[2024-10-11T00:30:07.512+0000] {processor.py:186} INFO - Started process (PID=1221) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:30:07.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:30:07.519+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:30:07.519+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:30:07.559+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:30:07.551+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
ModuleNotFoundError: No module named 'modules.armado_df'
[2024-10-11T00:30:07.561+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:30:07.586+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.083 seconds
[2024-10-11T00:30:37.927+0000] {processor.py:186} INFO - Started process (PID=1228) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:30:37.929+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:30:37.931+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:30:37.931+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:30:37.966+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:30:37.958+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
ModuleNotFoundError: No module named 'modules.armado_df'
[2024-10-11T00:30:37.969+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:30:37.989+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.067 seconds
[2024-10-11T00:31:08.556+0000] {processor.py:186} INFO - Started process (PID=1235) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:31:08.557+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:31:08.562+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:31:08.562+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:31:08.626+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:31:08.602+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
ModuleNotFoundError: No module named 'modules.armado_df'
[2024-10-11T00:31:08.633+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:31:08.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.114 seconds
[2024-10-11T00:31:38.867+0000] {processor.py:186} INFO - Started process (PID=1242) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:31:38.869+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:31:38.872+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:31:38.872+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:31:38.915+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:31:38.905+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .armado_df import creacion_df
ModuleNotFoundError: No module named 'modules.armado_df'
[2024-10-11T00:31:38.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:31:38.942+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.081 seconds
[2024-10-11T00:32:09.176+0000] {processor.py:186} INFO - Started process (PID=1249) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:32:09.178+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:32:09.187+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:32:09.187+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:32:09.251+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:32:09.242+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
ImportError: cannot import name 'creacion_df' from 'modules' (/opt/airflow/dags/modules/__init__.py)
[2024-10-11T00:32:09.253+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:32:09.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.115 seconds
[2024-10-11T00:32:39.597+0000] {processor.py:186} INFO - Started process (PID=1256) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:32:39.599+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:32:39.613+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:32:39.607+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:32:41.006+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:32:40.952+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:32:41.013+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:32:41.059+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 1.472 seconds
[2024-10-11T00:33:12.141+0000] {processor.py:186} INFO - Started process (PID=1267) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:33:12.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:33:12.147+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:33:12.146+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:33:12.244+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:33:12.220+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:33:12.248+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:33:12.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.141 seconds
[2024-10-11T00:33:42.499+0000] {processor.py:186} INFO - Started process (PID=1277) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:33:42.501+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:33:42.504+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:33:42.503+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:33:42.540+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:33:42.532+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:33:42.543+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:33:42.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.075 seconds
[2024-10-11T00:34:13.240+0000] {processor.py:186} INFO - Started process (PID=1285) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:34:13.245+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:34:13.248+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:34:13.248+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:34:13.332+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:34:13.319+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:34:13.340+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:34:13.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.128 seconds
[2024-10-11T00:34:43.841+0000] {processor.py:186} INFO - Started process (PID=1292) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:34:43.842+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:34:43.846+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:34:43.846+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:34:43.888+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:34:43.876+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:34:43.892+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:34:44.004+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.168 seconds
[2024-10-11T00:47:02.606+0000] {processor.py:186} INFO - Started process (PID=1293) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:47:02.617+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:47:02.670+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:47:02.663+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:47:02.836+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:47:02.774+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:47:02.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:47:03.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.870 seconds
[2024-10-11T00:47:38.562+0000] {processor.py:186} INFO - Started process (PID=1301) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:47:38.583+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:47:38.625+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:47:38.610+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:47:38.845+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:47:38.734+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:47:38.857+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:47:38.981+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.473 seconds
[2024-10-11T00:48:09.963+0000] {processor.py:186} INFO - Started process (PID=1308) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:48:09.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T00:48:09.974+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:48:09.973+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:48:10.017+0000] {logging_mixin.py:190} INFO - [2024-10-11T00:48:10.006+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T00:48:10.021+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T00:48:10.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.098 seconds
[2024-10-11T01:02:05.156+0000] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:02:05.157+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:02:05.161+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:02:05.160+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:02:05.217+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:02:05.202+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:02:05.221+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:02:05.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.108 seconds
[2024-10-11T01:02:48.984+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:02:48.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:02:49.577+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:02:49.574+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:02:49.767+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:02:49.736+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:02:49.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:02:49.992+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 2.438 seconds
[2024-10-11T01:03:20.520+0000] {processor.py:186} INFO - Started process (PID=67) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:03:20.521+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:03:20.524+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:03:20.524+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:03:20.653+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:03:20.638+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:03:20.658+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:03:20.676+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.163 seconds
[2024-10-11T01:03:51.245+0000] {processor.py:186} INFO - Started process (PID=73) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:03:51.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:03:51.251+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:03:51.251+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:03:51.327+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:03:51.310+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:03:51.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:03:51.360+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.123 seconds
[2024-10-11T01:04:21.837+0000] {processor.py:186} INFO - Started process (PID=80) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:04:21.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:04:21.841+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:04:21.841+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:04:21.892+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:04:21.880+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:04:21.897+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:04:21.914+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.082 seconds
[2024-10-11T01:04:52.077+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:04:52.079+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:04:52.082+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:04:52.081+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:04:52.144+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:04:52.123+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:04:52.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:04:52.168+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.096 seconds
[2024-10-11T01:08:10.099+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:08:10.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:08:10.106+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:08:10.105+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:08:10.176+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:08:10.156+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:08:10.184+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:08:10.218+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.129 seconds
[2024-10-11T01:08:40.799+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:08:40.801+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:08:40.805+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:08:40.804+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:08:40.860+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:08:40.844+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:08:40.863+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:08:40.883+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.089 seconds
[2024-10-11T01:09:11.202+0000] {processor.py:186} INFO - Started process (PID=105) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:09:11.204+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:09:11.210+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:09:11.209+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:09:11.259+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:09:11.245+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:09:11.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:09:11.290+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.097 seconds
[2024-10-11T01:09:41.546+0000] {processor.py:186} INFO - Started process (PID=112) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:09:41.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:09:41.553+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:09:41.553+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:09:41.615+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:09:41.600+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:09:41.620+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:09:41.641+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.101 seconds
[2024-10-11T01:10:11.871+0000] {processor.py:186} INFO - Started process (PID=119) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:10:11.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:10:11.881+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:10:11.880+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:10:11.962+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:10:11.939+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:10:11.966+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:10:11.998+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.133 seconds
[2024-10-11T01:10:42.090+0000] {processor.py:186} INFO - Started process (PID=126) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:10:42.091+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:10:42.094+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:10:42.094+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:10:42.157+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:10:42.141+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:10:42.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:10:42.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.099 seconds
[2024-10-11T01:13:30.389+0000] {processor.py:186} INFO - Started process (PID=56) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:13:30.391+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:13:30.393+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:13:30.393+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:13:30.434+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:13:30.423+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:13:30.440+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:13:30.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.081 seconds
[2024-10-11T01:14:08.810+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:14:08.832+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:14:08.919+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:14:08.892+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:14:09.739+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:14:09.534+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:14:09.819+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:14:09.947+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 1.410 seconds
[2024-10-11T01:14:40.392+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:14:40.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:14:40.401+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:14:40.400+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:14:40.428+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:14:40.421+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:14:40.429+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:14:40.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.067 seconds
[2024-10-11T01:15:12.153+0000] {processor.py:186} INFO - Started process (PID=82) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:15:12.865+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:15:12.871+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:15:12.870+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:15:13.337+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:15:13.242+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:15:13.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:15:14.992+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 2.843 seconds
[2024-10-11T01:15:45.288+0000] {processor.py:186} INFO - Started process (PID=90) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:15:45.289+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:15:45.291+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:15:45.291+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:15:45.318+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:15:45.310+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:15:45.320+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:15:45.336+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.052 seconds
[2024-10-11T01:16:15.532+0000] {processor.py:186} INFO - Started process (PID=97) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:16:15.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:16:15.536+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:16:15.536+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:16:15.589+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:16:15.576+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:16:15.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:16:15.613+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.087 seconds
[2024-10-11T01:16:46.468+0000] {processor.py:186} INFO - Started process (PID=104) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:16:46.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:16:46.473+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:16:46.472+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:16:46.531+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:16:46.515+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:16:46.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:16:46.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.094 seconds
[2024-10-11T01:27:53.186+0000] {processor.py:186} INFO - Started process (PID=111) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:27:53.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
[2024-10-11T01:27:53.227+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:27:53.225+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:27:53.357+0000] {logging_mixin.py:190} INFO - [2024-10-11T01:27:53.332+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/etl-airflow-fake_store.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/etl-airflow-fake_store.py", line 6, in <module>
    from modules import creacion_df, transformaciones, carga_datos
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from .build_df import creacion_df
  File "/opt/airflow/dags/modules/build_df.py", line 1, in <module>
    import pyspark as ps
ModuleNotFoundError: No module named 'pyspark'
[2024-10-11T01:27:53.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:27:53.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/etl-airflow-fake_store.py took 0.410 seconds
[2024-10-11T01:28:28.688+0000] {processor.py:186} INFO - Started process (PID=120) to work on /opt/airflow/dags/etl-airflow-fake_store.py
[2024-10-11T01:28:28.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/etl-airflow-fake_store.py for tasks to queue
